"""Writer agent: formats curated articles into a polished news digest."""

from __future__ import annotations

from datetime import UTC, datetime

from agent_framework._agents import Agent
from shon_toolkit.client import get_chat_client
from shon_toolkit.log import log
from shon_toolkit.middleware import llm_call_logging

from newsroom.models.article import DigestOutput, ScoredArticle

WRITER_PROMPT = """\
You are a tech news digest writer. You receive curated, scored articles and must
produce a polished daily news digest in Markdown format.

Format:
# 🗞️ OpenClaw Daily — {date}

> One-line editorial summary of today's top themes.

## 🔥 Top Stories
(Top 3-5 highest-scoring articles with rich summaries)

### [Title](url)
**Source** · relevance/novelty context
Brief editorial summary (2-3 sentences). Why this matters.

## 📡 Also Notable
(Next 5-10 articles, briefer format)

- **[Title](url)** — One-line summary. *(Source)*

## 🚀 Trending on GitHub
(If any GitHub repos were found)

- **[repo/name](url)** ⭐ stars_today — Description

---
*Generated by OpenClaw Newsroom*

Guidelines:
- Write engaging, editorial-quality summaries — not just restatements
- Group related stories together
- Highlight why each story matters to AI/ML practitioners
- Use emoji sparingly but effectively for visual scanning
- Keep the entire digest concise and scannable
"""


async def write_digest(articles: list[ScoredArticle]) -> str:
    if not articles:
        return _empty_digest()

    agent = Agent(
        client=get_chat_client(),
        name="digest-writer",
        instructions=WRITER_PROMPT,
        middleware=[llm_call_logging],
    )

    today = datetime.now(UTC).strftime("%B %d, %Y")
    articles_text = _format_articles_for_prompt(articles)

    prompt = (
        f"Today's date: {today}\n\n"
        f"Here are {len(articles)} curated articles (sorted by score):\n\n"
        f"{articles_text}\n\n"
        "Write the daily digest in the format specified."
    )

    log.info("Writer composing digest from %d articles", len(articles))
    response = await agent.run(prompt, options={"response_format": DigestOutput})

    if response.value:
        return response.value.markdown

    return response.text


def _format_articles_for_prompt(articles: list[ScoredArticle]) -> str:
    lines: list[str] = []
    for i, sa in enumerate(articles, 1):
        a = sa.article
        lines.append(
            f"{i}. [{sa.overall_score:.2f}] {a.title}\n"
            f"   URL: {a.url}\n"
            f"   Source: {a.source}\n"
            f"   Summary: {a.summary[:200]}\n"
            f"   Tags: {', '.join(a.tags)}\n"
            f"   Editor: {sa.reasoning}"
        )
    return "\n\n".join(lines)


def _empty_digest() -> str:
    today = datetime.now(UTC).strftime("%B %d, %Y")
    return (
        f"# 🗞️ OpenClaw Daily — {today}\n\n"
        "> No articles discovered today. All sources were quiet.\n\n"
        "---\n*Generated by OpenClaw Newsroom*\n"
    )
